version: '3.7'

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
  
  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - "nginx:backend"
    ports:
      - "80:8080"
