FROM ubuntu as builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq install cowsay && \
    apt-get clean && rm -fr /var/lib/apt/lists

RUN /usr/games/cowsay "Mooo! Mooo!" > /root/index.html

FROM nginx

COPY --from=builder /root/index.html /usr/share/nginx/html/index.html
COPY nginx_default.conf /etc/nginx/conf.d/default.conf
