---
apiVersion: v1
kind: Pod
metadata:
  name: proxypods
  labels:
    app: proxypods
spec:
  containers:
    - name: nginx
      image: gcr.io/myplaygrounds-paugarcia/nginx_container:latest
      ports: 
        - name: serveweb
          #expose port 8080 from the container
          containerPort: 5000
          #map port 8080 from the container to the 80 on the host
          #hostPort: 80
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
    - name: haproxy
      image: gcr.io/myplaygrounds-paugarcia/haproxy_container:latest
      ports: 
        - name: proxylisten
          #expose port 5000 from the port
          containerPort: 8080
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  client_id: ODUyMjY1ODc0NjU3LWliajRwbnFtdTRvdXMzN3JvaDFxOHNuNjJwajM1cGlyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t 
  client_secret: Wk9DYmlfejN6S2VvTTJwRUZNSm9jOTVC 

---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: config-proxiedservice
  namespace: default
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-secret

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config:
      '{"ports": {"proxiedservice":"config-proxiedservice"}}'
  name: myproxysample
spec:
  selector:
    app: proxypods
  ports:
    - name: proxiedservice
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
