version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  nginx:
    image: nginx:alpine
    volumes:
      - ./webapp/public:/code
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf  
    links:
      - "db:database"
      - "php:php"
    ports:
      - "80:80"
  php:
    image: php:7-fpm
    command: sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"
    volumes:
      - ./webapp/public:/code        
    links:
      - "db:database"
