apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: haproxy-frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-frontend
spec:
  selector:
    matchLabels:
      app: haproxy-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: haproxy
        image: "gcr.io/myplaygrounds-inter/haproxy_container"
