apiVersion: v1
kind: Pod
metadata:
  name: bestone
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: gcr.io/myplaygrounds-inter/nginx_container
    ports:
    - containerPort: 5000
  # These containers are run during pod initialization
  - name: proxy
    image: gcr.io/myplaygrounds-inter/haproxy_container
    ports:
    - containerPort: 8080
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
