---
apiVersion: v1
kind: Pod
metadata:
  name: proxypods
  labels:
    app: proxypods
spec:
  containers:
    - name: nginx
      image: gcr.io/myplaygrounds-paugarcia/nginx_container:latest
      ports: 
        - name: serveweb
          containerPort: 5000
          hostPort: 80
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
    - name: haproxy
      image: gcr.io/myplaygrounds-paugarcia/haproxy_container:latest
      ports: 
        - name: proxylisten
          containerPort: 8080
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: myproxysample
spec:
  selector:
    app: proxypods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
