runtime: python37

instance_class: F2

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /templates
  static_files: templates/index.html
  upload: templates/index.html
- url: /static
  static_files: static/logic.js
  upload: static/logic.js 
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /key
  static_files: key/sakey.json
  upload: key/sakey.json
- url: /.*
  script: auto
